apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  labels:
    app: jaeger-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-all-in-one
  template:
    metadata:
      name: jaeger-all-in-one
      labels:
        app: jaeger-all-in-one
    spec:
      containers:
        - name: all-in-one
          image: jaegertracing/all-in-one:{{ required "version must be specified" .Values.version }}
          ports:
          - containerPort: 5775
            protocol: UDP
          - containerPort: 6831
            protocol: UDP
          - containerPort: 6832
            protocol: UDP
          - containerPort: 16686
            protocol: TCP
          - containerPort: 9411
            protocol: TCP
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"